CRMS/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('consultant.urls','consultant'),namespace='consultant')),
    path('',include(('customer.urls','customer'),namespace='customer')),
    path('',include(('insurance.urls','insurance'),namespace='insurance'))
]

consultant/urls.py
from django.urls import path
from .views import my_page_cons, turn_request_to_not_show, download_pdf, consultant_view, payment_dates_cons_view

urlpatterns = [
    path('my_page_cons/<int:pk>/',my_page_cons,name='my_page_cons_url'),
    path('turn_request_to_not_show/<int:request_pk>/',turn_request_to_not_show,name='turn_request_to_not_show_url'),
    path('download_documents/<int:pk>/', download_pdf, name='download_pdf'),
    path('consultant/<int:pk>/', consultant_view, name='consultant_url'),
    path('payment_dates_cons/<int:ins_pk>/', payment_dates_cons_view, name='payment_dates_cons_url')
]

customer/urls.py
from django.urls import path
from .views import my_page, login_view, logout_view, signup_view, customer_view

urlpatterns = [
    path('my_page/<int:pk>/',my_page,name='my_page_url'),
    path('login/', login_view, name='login_url'),
    path('logout/', logout_view, name='logout_url'),
    path('Sign_up/', signup_view, name='sign_up_url'),
    path('customer/<int:pk>', customer_view, name='customer_url')
]

insurance/urls.py
from django.urls import path
from .views import home_view, sign_up_insurance, pay, use_request, payment_dates_view, insurances

urlpatterns = [
    path('',home_view,name='home_url'),
    path('sign_up_insurance/<int:pk>/',sign_up_insurance,name='sign_up_insurance_url'),
    path('pay/<str:date>/<int:ins_pk>/',pay,name='pay_url'),
    path('use_request/<int:ins_pk>',use_request,name='use_request_url'),
    path('payment_dates/<int:ins_pk>',payment_dates_view,name='payment_date_url'),
    path('insurances/', insurances, name='insurances_url')
]

consultant/models.py
from django.db import models
from customer.models import Customer


class Consultant(Customer):
    salary = models.FloatField(max_length=250, blank=False)

customer/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Customer(AbstractUser):
    # username inherits from AbstractUser
    # password inherits from AbstractUser
    first_name = models.CharField(max_length=150, blank=False)
    last_name = models.CharField(max_length=150, blank=False)
    phone_number = models.CharField(max_length=11, blank=False)
    address = models.CharField(max_length=250, blank=False)
    natural_number = models.CharField(max_length=20, blank=False)
    kind = models.CharField(max_length=10, choices=(('1', 'customer'),('2', 'consultant')), default='1')

    def __str__(self):
        return self.first_name + ' ' + self.last_name

insurance/models.py
from django.db import models
from customer.models import Customer
from consultant.models import Consultant


class Insurance(models.Model):
    cost_per_year = {1: 300000,
                     2: 400000,
                     3: 500000,
                     4: 300000,
                     5: 200000,
                     6: 250000,
                     7: 600000,
                     8: 600000,
                     9: 500000,
                     10: 1000000}
    Choices = (
        (1, 'بدنه ماشین'), (2, 'شخص ثالث'), (3, 'حوادث'), (4, 'درمان'), (5, 'عمر'), (6, 'واحد مسکونی'),
        (7, 'مرکز صنعتی'), (8, 'مرکز غیر صنعتی'), (9, 'حمل و نقل'), (10, 'هواپیما'))
    name = models.IntegerField(blank=False, choices=(Choices))
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, related_name='insurance_from_customer', null=True)
    consultant = models.ForeignKey(Consultant, on_delete=models.SET_NULL, related_name='insurance_from_consultant',
                                   null=True, blank=True)
    created_at = models.DateField()
    duration = models.IntegerField(
        choices=((1, 'یک سال'), (5, '5 سال'), (10, '10 سال'), (15, '15 سال'), (30, '30 سال'),))
    cost = models.FloatField(max_length=150, blank=False)
    payment_kind = models.CharField(max_length=15, choices=(('1', 'سالانه'), ('2', 'ماهانه')))

    @property
    def name_value(self):
        for (i, j) in self.Choices:
            if i == self.name:
                return j

    @property
    def payment_kind_value(self):
        if self.payment_kind == '1':
            return 'سالانه'
        return 'ماهانه'

    @property
    def expire_date(self):
        return self.created_at.replace(year=self.created_at.year + self.duration)

    @property
    def payment_count(self):
        if self.payment_kind == '1':
            return int(self.duration)
        else:
            return int(self.duration) * 12

    @property
    def cost_money(self):
        num = int(self.cost)
        return str('{:,}'.format(num))

    @property
    def payment_amount(self):
        num = int(self.cost / self.payment_count)
        return str('{:,}'.format(num))

    @property
    def not_paid_dates(self):
        for i in self.payment_dates_from_insurance.all():
            if not i.paid:
                return True

    @property
    def paid_dates(self):
        for i in self.payment_dates_from_insurance.all():
            if i.paid:
                return True

    def __str__(self):
        return self.name_value + ' ' + self.customer.username


class Payment_dates(models.Model):
    date = models.DateField()
    paid_date = models.DateField(null=True,blank=True)
    paid = models.BooleanField(default=False)
    insurance = models.ForeignKey(Insurance, on_delete=models.SET_NULL, related_name='payment_dates_from_insurance',
                                  null=True)

    def pay(self):
        self.paid = True

    def __str__(self):
        return self.insurance.__str__() + str(self.date)


class Bank_card(models.Model):
    card_number = models.IntegerField(blank=False)
    shaba_number = models.IntegerField(blank=False)
    bank_name = models.CharField(max_length=150, blank=False)
    owner = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='Bank_card_from_user', null=True)

    def __str__(self):
        return self.owner.__str__() + ' ' + self.bank_name


class Use_insurance(models.Model):
    request_content = models.CharField(max_length=500, default='')
    request_answer = models.CharField(max_length=500, default='', blank=True)
    request_date = models.DateField()
    amount = models.FloatField(max_length=150, default=0)
    recieve_card = models.ForeignKey(Bank_card, on_delete=models.SET_NULL, related_name='use_insurance_from_card',
                                     null=True)
    documents = models.FileField(default='')
    insurance = models.ForeignKey(Insurance, on_delete=models.CASCADE, related_name='use_insurance_from_insurance',
                                  null=True)
    paid = models.BooleanField(default=False)
    paid_date = models.DateField(null=True, blank=True)
    show_to_consultant = models.BooleanField(default=True)

    def __str__(self):
        return self.insurance.__str__() + ' ' + str(self.request_date)

consultant/views.py
import datetime
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect, FileResponse
from .models import Consultant
from insurance.models import Insurance
from insurance.models import Use_insurance


def my_page_cons(request, pk):
    user = get_object_or_404(Consultant, pk=pk)
    if request.method == 'POST':
        use_insurance1 = Use_insurance.objects.get(pk=request.POST['request_pk'])
        answer_content = request.POST['request_answer']
        use_insurance1.request_answer = use_insurance1.request_answer + answer_content + '/'
        if 'paid' in request.POST:
            use_insurance1.paid = True
            use_insurance1.paid_date = datetime.datetime.today()
        use_insurance1.save()
        return HttpResponseRedirect(reverse('consultant:my_page_cons_url', args=(user.pk,)))
    delayed_dates = []
    today_payments = []
    for ins in user.insurance_from_consultant.all():
        for payment_date in ins.payment_dates_from_insurance.all():
            if not payment_date.paid:
                if payment_date.date < datetime.date.today():
                    delayed_dates.append(payment_date)
                elif payment_date.date == datetime.date.today():
                    today_payments.append(payment_date)
    return render(request, 'My_page_cons.html',
                  {'user': user, 'today_payments': today_payments, 'delayed_dates': delayed_dates})


def turn_request_to_not_show(request, request_pk):
    use_insurance1 = Use_insurance.objects.get(pk=request_pk)
    consultant1 = use_insurance1.insurance.consultant
    use_insurance1.show_to_consultant = False
    use_insurance1.save()
    return HttpResponseRedirect(reverse('consultant:my_page_cons_url', args=(consultant1.pk,)))


def download_pdf(request, pk):
    use_insurance1 = Use_insurance.objects.get(pk=pk)
    pdf_file = use_insurance1.documents
    response = FileResponse(pdf_file, content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="documents.pdf"'
    return response


def consultant_view(request, pk):
    consultant1 = Consultant.objects.get(pk=pk)
    return render(request, 'consultant.html', {'consultant': consultant1})


def payment_dates_cons_view(request, ins_pk):
    insurance1 = Insurance.objects.get(pk=ins_pk)
    return render(request, 'Payment_dates_cons.html', {'insurance': insurance1})

customer/views.py
import datetime
from django.contrib.auth import login, logout
from django.shortcuts import render, get_object_or_404, reverse
from .models import Customer
from django.http import HttpResponseRedirect


def signup_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        phone_number = request.POST['phone_number']
        address = request.POST['address']
        natural_number = request.POST['natural_number']
        customer1 = Customer.objects.create(username=username, password=password, first_name=first_name,
                                            last_name=last_name, phone_number=phone_number, address=address,
                                            natural_number=natural_number)
        customer1.save()
        return HttpResponseRedirect(reverse("customer:login_url"))
    return render(request, 'Sign_up.html')


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        try:
            customer1 = Customer.objects.get(username=username, password=password)
        except:
            customer1 = None
        if customer1 is not None:
            login(request, customer1)
            if customer1.kind == '1':
                return HttpResponseRedirect(reverse("customer:my_page_url", args=(customer1.pk,)))
            else:
                return HttpResponseRedirect(reverse("consultant:my_page_cons_url", args=(customer1.pk,)))
        else:
            return HttpResponseRedirect(reverse('customer:login_url'))
    return render(request, 'Login.html')


def logout_view(request):
    logout(request)
    return render(request, 'Home.html')


def my_page(request, pk):
    user = get_object_or_404(Customer, pk=pk)
    insurances = user.insurance_from_customer.all()
    payment_dates = []
    delayed_dates = []
    for ins in insurances:
        for payment_date in ins.payment_dates_from_insurance.all():
            if not payment_date.paid:
                if payment_date.date >= datetime.date.today():
                    payment_dates.append([payment_date, payment_date.date])
                if payment_date.date < datetime.date.today():
                    delayed_dates.append(payment_date)
    payment_dates.sort(key=lambda l: l[1])
    try:
        closest_payment = payment_dates[0][0]
    except:
        closest_payment = ''
    return render(request, 'My_page.html',
                  {'user': user, 'closest_payment': closest_payment, 'delayed_dates': delayed_dates})


def customer_view(request, pk):
    customer1 = Customer.objects.get(pk=pk)
    return render(request, 'customer.html', {'customer': customer1})

insurance/views.py
import datetime
from django.shortcuts import render, reverse
from .models import Insurance, Payment_dates, Customer, Bank_card, Use_insurance
from django.http import HttpResponseRedirect


def home_view(request):
    return render(request, 'Home.html')


def sign_up_insurance(request, pk):
    cost_per_year = Insurance.cost_per_year
    if request.method == 'POST':
        name = request.POST['name']
        created_at = datetime.date.today()
        duration = request.POST['duration']
        payment_kind = request.POST['payment_kind']
        insurance1 = Insurance.objects.create(name=name, customer_id=pk, created_at=created_at, duration=duration,
                                              cost=cost_per_year[int(name)] * int(duration), payment_kind=payment_kind)
        insurance1.save()
        if payment_kind == '2':
            month = created_at.month
            year = created_at.year
            for i in range(int(insurance1.payment_count)):
                payment_date1 = Payment_dates(date=created_at.replace(month=month, year=year), insurance=insurance1)
                payment_date1.save()
                month += 1
                if month == 13:
                    month = 1
                    year += 1
        else:
            year = created_at.year
            for i in range(int(insurance1.payment_count)):
                payment_date1 = Payment_dates(date=created_at.replace(year=year), insurance=insurance1)
                payment_date1.save()
                year += 1
        return HttpResponseRedirect(reverse("customer:my_page_url", args=(pk,)))
    return render(request, 'Sign_up_insurance.html')


def pay(request, date, ins_pk):
    date = datetime.datetime.strptime(date, '%Y-%m-%d').date()
    payment1 = Payment_dates.objects.get(insurance_id=ins_pk, date=date)
    payment1.paid = True
    payment1.paid_date = datetime.datetime.today()
    payment1.save()
    return HttpResponseRedirect(reverse("insurance:payment_date_url", args=(ins_pk,)))


def use_request(request, ins_pk):
    if request.method == 'POST':
        card_number = request.POST['card_number']
        shaba_number = request.POST['shaba_number']
        bank_name = request.POST['bank_name']
        owner_pk = Insurance.objects.get(pk=ins_pk).customer.pk
        recieve_card = Bank_card.objects.create(card_number=card_number, shaba_number=shaba_number, bank_name=bank_name,
                                                owner_id=owner_pk)
        recieve_card.save()
        recieve_card_pk = recieve_card.pk
        request_content = request.POST['request_content']
        request_date = datetime.date.today()
        amount = request.POST['amount']
        documents = request.POST['documents']
        use_insurance1 = Use_insurance.objects.create(request_content=request_content, request_date=request_date,
                                                      amount=amount, recieve_card_id=recieve_card_pk,
                                                      documents=documents,
                                                      insurance_id=ins_pk)
        use_insurance1.save()
        return HttpResponseRedirect(reverse('customer:my_page_url', args=(owner_pk,)))
    else:
        return render(request, 'Use_insurance_request.html')


def payment_dates_view(request, ins_pk):
    insurance1 = Insurance.objects.get(pk=ins_pk)
    return render(request, 'Payment_dates.html', {'insurance': insurance1})


def insurances(request):
    return render(request, 'insurances.html')

templates/Home.html
{% extends 'header_footer.html' %}

{% block title %}
    سامانه ارتباط با مشتری
{% endblock %}
{% block content %}
    <main class="container" dir="rtl">
        <br>
        <div class="row mb-2">
            <div class="col-12">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <div class="mb-1 text-body-secondary">
                            سامانه ارتباط با مشتری در بیمه
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/My_page.html
{% extends 'header_footer.html' %}
{% load jalali_tags %}

{% block title %}
    صفحه من
{% endblock %}
{% block content %}
    <main class="container" dir="rtl">
        <div class="p-4 p-md-5 mb-4 rounded user_profile">
            <div class="col-lg-6 px-0">
                <h3>{{ user.get_full_name }}</h3>
                <br>
                <p>نام کاربری : {{ user.username }}</p>
                <p>شماره تماس : {{ user.phone_number }}</p>
                <p>آدرس : {{ user.address }}</p>
            </div>
        </div>

        <h3 class="p-3">قسط های عقب افتاده :</h3>

        <div class="row mb-2">
            <div class="col-12">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        {% if delayed_dates %}
                            {% for payment_date in delayed_dates %}
                                پرداخت در تاریخ {{ payment_date.date|to_jalali:'%y/%m/%d' }} برای بیمه
                                {{ payment_date.insurance.name_value }}
                            {% endfor %}
                        {% else %}
                            شما هیچ پرداخت عقب افتاده ای ندارید
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <h3 class="p-3">قسط بعدی شما :</h3>

        <div class="row mb-2">
            <div class="col-12">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    {% if closest_payment %}
                        <div class="col p-4 d-flex flex-column position-static">
                            قسط بعدی شما در تاریخ {{ closest_payment.date|to_jalali:'%y/%m/%d' }} برای
                            بیمه {{ closest_payment.insurance.name_value }} است.
                        </div>
                    {% else %}
                        <div class="col p-4 d-flex flex-column position-static">
                            شما هیچ پرداخت بعدی ای ندارید
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <h3 class="p-3">بیمه ها :</h3>
        <br>

        <div class="row mb-2">
            {% for ins in user.insurance_from_customer.all %}
                <div class="col-md-6">
                    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                        <div class="col p-4 d-flex flex-column position-static">
                            <h3 class="mb-0">{{ ins.name_value }}</h3>
                            <br>
                            <div class="mb-1 text-body-secondary">تاریخ خرید
                                : {{ ins.created_at|to_jalali:'%y/%m/%d' }}</div>
                            {% if ins.consultant %}
                                <div class="mb-1 text-body-secondary">مشاور : <a
                                        href="{% url 'consultant:consultant_url' ins.consultant.pk %}">{{ ins.consultant.get_full_name }}</a>
                                </div>
                            {% else %}
                                <div class="mb-1 text-body-secondary">مشاور : بزودی توسط مدیریت شرکت تعیین میشود!</div>
                            {% endif %}
                            <div class="mb-1 text-body-secondary">مدت زمان : {{ ins.duration }} سال</div>
                            <div class="mb-1 text-body-secondary">انقضا
                                : {{ ins.expire_date|to_jalali:'%y/%m/%d' }}</div>
                            <div class="mb-1 text-body-secondary">هزینه کل : {{ ins.cost_money }} تومان</div>
                            <div class="mb-1 text-body-secondary">نحوه پرداخت اقساط : {{ ins.payment_kind_value }}</div>
                            <br>
                            <a href="{% url 'insurance:payment_date_url' ins.pk %}">
                                برنامه پرداخت ها
                            </a>
                            <a href="{% url 'insurance:use_request_url' ins.pk %}">
                                درخواست دریافت پول
                            </a>
                        </div>
                        <div class="col-auto d-none d-lg-block">
                            <svg class="bd-placeholder-img" width="200" height="350" xmlns="http://www.w3.org/2000/svg"
                                 role="img" preserveAspectRatio="xMidYMid slice"
                                 focusable="false"><title>Placeholder</title>
                                <rect width="100%" height="100%" fill="#00719c"></rect>
                            </svg>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <a href="{% url 'insurance:sign_up_insurance_url' user.pk %}" class="btn btn-primary btn-lg">خرید بیمه جدید</a>
        <br><br>
        <h3 class="p-3">درخواست های پرداخت :</h3>
        <div class="row mb-2">
            {% for ins in user.insurance_from_customer.all %}
                {% for request in ins.use_insurance_from_insurance.all %}
                    <div class="col-12">
                    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                        <div class="col p-4 d-flex flex-column position-static">
                            <h5 class="mb-0">درخواست برای {{ ins.name_value }}</h5>
                            <br>
                            <div class="mb-1 text-body-secondary">
                                متن درخواست : {{ request.request_content }}
                            </div>
                            <div class="mb-1 text-body-secondary">
                                تاریخ درخواست : {{ request.request_date|to_jalali:'%y/%m/%d' }}
                            </div>
                            <div class="mb-1 text-body-secondary">
                                کارت بانک انتخابی برای دریافت پول : بانک {{ request.recieve_card.bank_name }} شماره
                                کارت {{ request.recieve_card.card_number }}
                            </div>
                        </div>
                        <div class="p-3 text-left">
                            <button onclick="$('#condition').toggle();" class="btn btn-primary btn-sm">وضعیت درخواست
                            </button>
                        </div>
                        <div id="condition" style="display: none">
                            <div class="col p-4 d-flex flex-column position-static">
                                <div class="mb-1 text-body-secondary">
                                    {% if request.request_answer %}
                                        پاسخ مشاور : {{ request.request_answer }}
                                    {% else %}
                                        پاسخ مشاور : درخواست شما هنوز توسط مشاور بیمه شما بررسی نشده.
                                    {% endif %}
                                </div>
                                <div class="mb-1 text-body-secondary">
                                    {% if request.paid %}
                                        وضعیت پرداخت : مبلغ درخواستی شما در تاریخ
                                        {{ request.paid_date|to_jalali:'%y/%m/%d' }} پرداخت شده است.
                                    {% else %}
                                        وضعیت پرداخت : پرداخت نشده.
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endfor %}
            </div>

            <br>

    </main>
{% endblock %}

templates/consultant.html
{% extends 'header_footer.html' %}
{% load jalali_tags %}

{% block title %}
    صفحه مشاور
{% endblock %}
{% block content %}
    <main class="container" dir="rtl">
        <div class="p-4 p-md-5 mb-4 rounded user_profile">
            <div class="col-lg-6 px-0">
                <h3>{{ consultant.get_full_name }}</h3>
                <br>
                <p>نام کاربری : {{ consultant.username }}</p>
                <p>شماره تماس : {{ consultant.phone_number }}</p>
            </div>
        </div>
    </main>
{% endblock %}

templates/customer.html
{% extends 'header_footer.html' %}
{% load jalali_tags %}

{% block title %}
    صفحه مشتری
{% endblock %}
{% block content %}
    <main class="container" dir="rtl">
        <div class="p-4 p-md-5 mb-4 rounded user_profile">
            <div class="col-lg-6 px-0">
                <h3>{{ customer.get_full_name }}</h3>
                <br>
                <p>نام کاربری : {{ customer.username }}</p>
                <p>شماره تماس : {{ customer.phone_number }}</p>
                <p>آدرس : {{ customer.address }}</p>
            </div>
        </div>
        <div class="row mb-2">
            {% for ins in customer.insurance_from_customer.all %}
                <div class="col-12">
                    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                        <div class="col p-4 d-flex flex-column position-static">
                            <h3 class="mb-0">{{ ins.name_value }}</h3>
                            <br>
                            <div class="mb-1 text-body-secondary">تاریخ خرید
                                : {{ ins.created_at|to_jalali:'%y/%m/%d' }}</div>
                            <div class="mb-1 text-body-secondary">مدت زمان : {{ ins.duration }} سال</div>
                            <div class="mb-1 text-body-secondary">انقضا
                                : {{ ins.expire_date|to_jalali:'%y/%m/%d' }}</div>
                            <div class="mb-1 text-body-secondary">هزینه کل : {{ ins.cost_money }} تومان</div>
                            <div class="mb-1 text-body-secondary">نحوه پرداخت اقساط : {{ ins.payment_kind_value }}</div>
                            <a href="{% url 'consultant:payment_dates_cons_url' ins.pk %}">
                                برنامه پرداخت ها
                            </a>
                        </div>
                        <div class="col-auto d-none d-lg-block">
                            <svg class="bd-placeholder-img" width="200" height="300" xmlns="http://www.w3.org/2000/svg"
                                 role="img" preserveAspectRatio="xMidYMid slice"
                                 focusable="false"><title>Placeholder</title>
                                <rect width="100%" height="100%" fill="#00719c"></rect>
                            </svg>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </main>
{% endblock %}

templates/header_footer.html
<!DOCTYPE html>
{% load static %}
<html lang="fa">
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
    <script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>
</head>
<body class="container">
<nav class="navbar navbar-expand-lg navbar-light menu_color" dir="rtl">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'insurance:home_url' %}">CRMS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'insurance:home_url' %}">خانه</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'insurance:insurances_url' %}">بیمه ها</a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'customer:login_url' %}">ورود</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'customer:logout_url' %}">خروج</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer:sign_up_url' %}">ایجاد حساب کاربری</a>
                </li>
                {% if user.is_authenticated %}
                    {% if user.kind == '1' %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:my_page_url' user.pk %}">صفحه من</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'consultant:my_page_cons_url' user.pk %}">صفحه من</a>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 mb-0 text-muted">&copy; صبا فتحی ، شقایق امینی </p>
        <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item"><a href="{% url 'insurance:home_url' %}" class="nav-link px-2 text-muted">خانه</a></li>
            <li class="nav-item"><a href="{% url 'insurance:insurances_url' %}" class="nav-link px-2 text-muted">بیمه ها</a></li>
            {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'insurance:sign_up_insurance_url' user.pk %}"
                                        class="nav-link px-2 text-muted">خرید بیمه</a></li>
            {% else %}
                <li class="nav-item"><a href="{% url 'customer:login_url' %}" class="nav-link px-2 text-muted">خرید
                    بیمه</a></li>
            {% endif %}
        </ul>
    </footer>
</div>
</body>
</html>